[package]
name = "sqlite"
version = "0.1.0"
authors = ["Ibnu Yahya <anak10thn@gmail.com>"]

[dependencies]
sqlite = "0.25.0"
serde_json = "1.0"
libc = "0.2.62"

[[bin]]
name = "sqlite"
doc = false
path = "src/lib.rs"

[lib]
name = "sqlite"
crate-type = ["dylib"]